<h1>Welcome Netboffin</h1>
<h2>Here is a list of your projects</h2>
<script type="text/javascript">
$(document).ready(function(){
$(".health_check").hide();

});
</script>

<ul id="project_list">
<li>
<h2><a href="projects/user1/1">Project 1</a><a href="#" onclick="$('#project_1_health_check').toggle();"><img class="health_icon" src="images/health_icon.png" /></a></h2>
<div id="project_1_health_check" class="health_check">
<table>
<tr><th colspan="4">Project 1 Health Check</th>
</tr>
<tr><td></td><td>%</td><td>%</td><td></td></tr>
<tr><td>Checklist</td><td>Completed</td><td>Acceptable</td><td>Rating</td></tr>

<tr><td>1 - Starting up a Project</td><td></td><td></td><td></td></tr>
<tr><td>2 - Directing a Project</td><td></td><td></td><td></td></tr>
<tr><td>3 - Initiating a Project</td><td></td><td></td><td></td></tr>
<tr><td>4 - Controlling a Stage</td><td></td><td></td><td></td></tr>
<tr><td>5 - Managing Product Delivery</td><td></td><td></td><td></td></tr>
<tr><td>6 - Managing a Stage Boundary</td><td></td><td></td><td></td></tr>
<tr><td>7 - Closing a Project</td><td></td><td></td><td></td></tr>
<tr><td></td><td></td><td></td><td></td></tr>
<tr><td></td><td></td><td></td><td></td></tr>

</table>
</div>
</li>
<li><h2><a href="projects/user1/1">Project 2</a><a href="#" onclick="$('#project_2_health_check').toggle();"><img class="health_icon" src="images/health_icon.png" /></a></h2>
<div id="project_2_health_check" class="health_check">
<table>
<tr><th colspan="4">Project 2</th>
</tr>
<tr><td></td><td>%</td><td>%</td><td></td></tr>
<tr><td>Checklist</td><td>Completed</td><td>Acceptable</td><td>Rating</td></tr>

<tr><td>1 - Starting up a Project</td><td></td><td></td><td></td></tr>
<tr><td>2 - Directing a Project</td><td></td><td></td><td></td></tr>
<tr><td>3 - Initiating a Project</td><td></td><td></td><td></td></tr>
<tr><td>4 - Controlling a Stage</td><td></td><td></td><td></td></tr>
<tr><td>5 - Managing Product Delivery</td><td></td><td></td><td></td></tr>
<tr><td>6 - Managing a Stage Boundary</td><td></td><td></td><td></td></tr>
<tr><td>7 - Closing a Project</td><td></td><td></td><td></td></tr>
<tr><td></td><td></td><td></td><td></td></tr>
<tr><td></td><td></td><td></td><td></td></tr>

</table>
</div>


</li>



</ul>
