<div id="view-content">
    <p class="company_header">netboffin</p>
    <style>.project_person{width:250px;float:left;}</style>
    <p class="people_project_header">Project 1</p>
	<div class="project_person" id="project_1">
            
            <div class="project_people_body">
                <ul>
                    <li><p class="people_name">Michael Brogan</p>
                        <img src="images/people/mick_brogan.jpg" width="75px" height="75px">
                        <p class="email">
                            michael@netboffin.com
                        </p>
                    </li>
                </ul>
            </div>
        </div>
        <div class="project_person project_1" id="project_1">
            
            <div class="project_people_body">
                <ul>
                    <li><p class="people_name">Paul Anderson</p>
                        <img src="images/people/paul_anderson.jpg" width="75px" height="75px">
                        <p class="email">
                            paul@netboffin.com
                        </p>
                    </li>
                </ul>
            </div>
        </div>

</div>