<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252" />
<title>Protoplan Projects</title>
<!-- Source File for yahoo reset and base class
<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.9.0/build/reset/reset-min.css"/>
<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.9.0/build/reset-fonts-grids/reset-fonts-grids.css"/>
-->
 <link href="css/basecamp_edited.css" rel="stylesheet" />
<link href="css/project_list.css" rel="stylesheet" />
<link href="css/maincontent.css" rel="stylesheet" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" type="text/javascript"></script>

<!--<link rel="stylesheet" type="text/css" href="/css/master.css" />-->


<body>
<div id="wrapper">
<div id="Header">
<h1>Protoplan<span>netboffin</span>
</h1>
<div id="navigation"><!-- end of navigation -->

<div id="Tabs">
<ul id="MainTabs" >
<li><a href="/projects/6393819-split-festival-ticketing-system/log">Overview</a></li>
<li><a href="/projects/6393819-split-festival-ticketing-system/log">Compare Projects</a></li>
<li><a href="/projects/6393819-split-festival-ticketing-system/log">Projects</a></li>
<li style="float:right"><a href="/projects/6393819-split-festival-ticketing-system/log">People</a></li>
<li style="float:right"><a href="/projects/6393819-split-festival-ticketing-system/log">Search</a></li>
<li style="float:right"><a href="/projects/6393819-split-festival-ticketing-system/log">Templates</a></li>
<li style="float:right"><a href="/projects/6393819-split-festival-ticketing-system/log">Settings</a></li>
</ul style="float:right"></div>
</div><!-- End of Tabs -->
</div><!-- End of header -->
<div id="maincontent">

<?php echo $this->layout()->content ?>



</div><!-- end of maincontent -->

<!-- <div class="push"></div> -->
</div><!-- end of wrapper -->

<!--<div id="footer">Footer</div> --><!-- end of footer -->
</body>
</html>