<div id="view-content">
    <p>Project 1 > Processes > Start-Up</p>
	<p>View script for controller <b>StartUp</b> and script/action name <b>index</b></p>
        <img src="images/process_su.gif">
       
        <div id="startup_products">
          Products produced during this process are as follows:
           <ul id="startup_documents">
                <li>Role descriptions</li>
                <li>Daily Log</li>
                <li>Lessons Log</li>
                <li>Outline Business Case</li>
                <li>Project Product Description</li>
                <li>Project Approach</li>
                <li>Project Brief</li>
                <li>Stage Plan</li>
            </ul>
        </div>

</div>